apiVersion: v2
name: domproxy
appVersion: 0.1.4
description: A generated Helm Chart for REASON IDO Domain Proxy Service
version: 0.0.1
type: application
maintainers:
  - name: cdecatapult
    url: cdecatapult.github.io/reason-helmcharts
dependencies:
  - name: postgresql
    version: '^12.x.x'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
